### ISSUE TITLE
Redmine 3.1.x compatiblity?

### ISSUE THREAD

**Issue by shawndibble** [johnson-logicmatter/leave_management_system#1]
Any plans on making this plugin compatible with redmine 3.1.x?

**Comment by meetdileep** [comment]
Hi. I am also interested in this plugin. Do you have any plans in migration to 3.x

**Comment by iuriifavi** [comment]
Also interested, maybe I can make some review and port it.... 
Please contact me.

**Comment by snehalgh** [comment]
Any plan for making this plugin compatible with redmine 3.1x?
